### PR TITLE
Feature/upgrade to dotnet 5

### PR DESCRIPTION
**Pull request by talktocory**
Hi,

I've upgraded the Core and Function projects to dotnet 5 and successfully deployed them to:

https://campaignkitworldmapfunction20210530183839.azurewebsites.net

Some notes about the upgrade:

- dotnet 5 functions now run as a [dotnet isolated process](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) instead of as a dll directly within the Azure Functions server runtime.  This necessitated a minor rewrite of the Startup.cs to Program.cs.  
- Visual Studio is not letting me use Docker for local testing/debugging on the upgraded Azure Function project.  The only containerization option is "Add Orchestration Support" which wants me to switch the project to a Windows image and use Azure Service Fabric.  I'm not 100% sure what's going on here.  It might be that local Docker testing/debugging support is ready yet in VisualStudio for dotnet 5 functions and will be coming in a future update.
- Currently on startup I launch the following for testing/debugging:
  - CampaignKit.WorldMap.Function using project launch configuration.
  - CampaignKit.WorldMap.UI using Docker image configuration.
- CI/CD from GitHub is not yet supported for dotnet 5 Azure Functions.  (see: below) This application needs to be manually deployed for the time being.  (I assume that this will change shortly)  When you deploy it manually you will be warned that you the runtime version is changing.

Cory

image

### CODE REVIEW

**Review by JochenLinnemann — COMMENTED** [review]
Interesting... I will look int o the pipeline thing first

**Comment by JochenLinnemann** [comment]
Sorry, I did not find time to look into pipeline stuff. Do you have any news, @talktocory?

**Comment by talktocory** [comment]
No.  Sorry @JochenLinnemann .  I've been absolutely swamped with work stuff.  Hope to get back into world-map stuff in the next few weeks.  Maybe by then Microsoft will have finished rolling out the pipeline support for dotnet 5 and it will be a non-issue.

**Comment by talktocory** [comment]
@JochenLinnemann - I think the code has achieved a stable state.  You can try it out here: https://campaignkitworldmapui20210530185544.azurewebsites.net/

Some notes:
- Azure Function polling is working correctly now.  Back in July there were some Azure bugs that prevented us from setting the interval we wanted to use.
- The Azure Function polling has been set to a five second interval.  This means that when a new map is created it will take a maximum of five seconds before the Azure Function begins processing images for the map.  I tried this with a 5MB image just now and the UI took 20 seconds from when I hit "Submit" until I began to see the progress bar registering progress.  Most of that 20 seconds is used to do the initial image upload from the client and to set things up in the Azure blob storage.
- Debugging locally works fine.  The UI runs in Docker Desktop and the function runs in Azure Function core tools.
image
- There is a bug with the Azure Function core tools that requires you to clear and redo your local storage.  If you see error messages like the one shown in the image below when debugging you need clear your Azure local storage.  More info [here](https://docs.microsoft.com/en-us/answers/questions/530444/timertrigger-function-net5-starting-worker-process.html).
image

I'd like to start working on CI/CD for this app.  There are two things I'll need your help with:
1. Temporarily remove the requirement here in GitHub to require a team review for pull requests into the 'develop' branch.  This is so I can keep triggering CI/CD without having to bug you.
2. Authorize GitHub to access our Azure DevOps pipeline.  I left instructions [here](https://dev.azure.com/jl-its/Campaign%20Logger/_sprints/taskboard/Campaign%20Logger%20Team/Campaign%20Logger/2021/2021-20?workitem=1704)

**Review by JochenLinnemann — APPROVED** [review]

**Comment by JochenLinnemann** [comment]
> @JochenLinnemann - I think the code has achieved a stable state. You can try it out here: https://campaignkitworldmapui20210530185544.azurewebsites.net/
> 
> Some notes:
> 
> * Azure Function polling is working correctly now.  Back in July there were some Azure bugs that prevented us from setting the interval we wanted to use.
> * The Azure Function polling has been set to a five second interval.  This means that when a new map is created it will take a maximum of five seconds before the Azure Function begins processing images for the map.  I tried this with a 5MB image just now and the UI took 20 seconds from when I hit "Submit" until I began to see the progress bar registering progress.  Most of that 20 seconds is used to do the initial image upload from the client and to set things up in the Azure blob storage.
> * Debugging locally works fine.  The UI runs in Docker Desktop and the function runs in Azure Function core tools.
>   image
> * There is a bug with the Azure Function core tools that requires you to clear and redo your local storage.  If you see error messages like the one shown in the image below when debugging you need clear your Azure local storage.  More info [here](https://docs.microsoft.com/en-us/answers/questions/530444/timertrigger-function-net5-starting-worker-process.html).
>   image
> 
> I'd like to start working on CI/CD for this app. There are two things I'll need your help with:
> 
> 1. Temporarily remove the requirement here in GitHub to require a team review for pull requests into the 'develop' branch.  This is so I can keep triggering CI/CD without having to bug you.
> 2. Authorize GitHub to access our Azure DevOps pipeline.  I left instructions [here](https://dev.azure.com/jl-its/Campaign%20Logger/_sprints/taskboard/Campaign%20Logger%20Team/Campaign%20Logger/2021/2021-20?workitem=1704)

Hi, Cory,

you can trigger a pipeline manually without pushing to develop:
image

Got to https://dev.azure.com/jl-its/Campaign%20Logger/_build?definitionId=11
Click Run Pipeline
Select your branch

**Pull request merged**
